- name: Provision a compute instance
  hosts: localhost
  gather_facts: no
  become: no
  vars:
    os_config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    os_auth:
      project_name: "{{ lookup('env', 'OS_PROJECT') }}"
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
      username: "{{ lookup('env', 'OS_USERNAME') }}"
      password: "{{ lookup('env', 'OS_PASSWORD') }}"
  vars_files:
    - test_vars.yml
  tasks:
    - name: Load Tower cloud credential config when it is present
      include_vars: "{{ os_config_file }}"
      when: os_config_file != ''
    - name: Set necessary variables when Tower cloud credential config is present
      set_fact:
        os_auth:
          auth_url: "{{ clouds.devstack.auth.auth_url }}"
          username: "{{ clouds.devstack.auth.username }}"
          password: "{{ clouds.devstack.auth.password }}"
          project_name: "{{ clouds.devstack.auth.project_name }}"
      when: os_config_file != ''
    - name: Fail if fallback environment variables are not set
      fail:
        msg: "missing required environment variable: '{{ item }}'"
      when: os_config_file == '' and lookup('env', item) is undefined
      with_items:
        - OS_AUTH_URL
        - OS_USERNAME
        - OS_PASSWORD
        - OS_PROJECT
        
    - name: echo command
      debug: msg="something {{ item }}['value']['apple']"
      with_items: "{{ fruits }}"
   
    - name: echo with dict
      debug: msg="something {{ item }}.apple"
      with_dict: "{{ fruits }}"
        
    - name: debug
      debug:
        msg: "something {{ os_auth }}"
    
    - name: debug
      debug:
        msg: "something {{ fruits }}"
        
    - name: debug dict
      debug:
        msg: "fruits numbers loop {{ item }}"
      with_items: "{{ fruits }}"
        
    - name: debug dict
      debug:
        msg: "fruits numbers loop {{ item.tomato }}, {{ item.potato }}"
      with_dict: "{{ vegitables }}"
      
    - name: Launch compute instances
      os_server:
        auth: "{{ os_auth }}"
        name: compute-node-demo
        auto_ip: no
        image: rhel-7.2
        flavor: m1.small
        key_name: demo-key
        nics:
          - net-name: direct
        security_groups:
          - ssh
        wait: no
        state: present
